# Generated by Django 3.2.6 on 2021-09-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('seller', models.CharField(default='Seller', max_length=100)),
                ('date_posted', models.DateField(auto_now=True)),
                ('bedrooms', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('bathrooms', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('sqfts', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('size', models.CharField(default='For Land only', max_length=100, null=True)),
                ('price', models.CharField(default='Negotiable', max_length=30)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('image_1', models.ImageField(upload_to='images')),
                ('image_2', models.ImageField(upload_to='images')),
                ('image_3', models.ImageField(upload_to='images')),
                ('image_4', models.ImageField(upload_to='images')),
                ('image_5', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.region')),
            ],
            options={
                'ordering': ('-date_posted', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='main.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='main.region')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
