# Generated by Django 3.2.6 on 2021-09-13 17:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='okay', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='okay', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='okay', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='okay', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
