# Generated by Django 3.2.6 on 2021-09-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210913_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_description',
            field=models.CharField(default='okay', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqfts',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
