# Generated by Django 3.2.6 on 2021-09-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210913_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=255)),
                ('date_posted', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_posted', '-id'),
            },
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
