# Generated by Django 3.2.6 on 2021-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_listings_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type_for',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Lease', 'Lease')], default='Rent', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
