# Generated by Django 3.2.6 on 2021-09-20 11:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
