# Generated by Django 3.2.6 on 2021-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
