# Generated by Django 3.2.6 on 2021-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_property_image_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_6',
            field=models.ImageField(upload_to='images'),
        ),
    ]
