# Generated by Django 3.2.6 on 2021-09-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_property_image_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
