# Generated by Django 3.2.6 on 2021-09-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_property_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
