# Generated by Django 3.2.6 on 2021-09-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='propert',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.property'),
            preserve_default=False,
        ),
    ]
