# Generated by Django 3.2.6 on 2021-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_booking_propert'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_units',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
